version: '3'
services:
  backend:
    build:
      context: ./contacts-backend
      dockerfile: Dockerfile
    container_name: contacts_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/contacts_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: "wget --spider --quiet localhost:9090/api/contacts"
      interval: 5s
      timeout: 5s
      retries: 8
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9090:9090"

  frontend:
    build:
      context: ./contacts-frontend
      dockerfile: Dockerfile
    container_name: contacts_frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"

  db:
    image: mysql
    container_name: contacts_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacts_db
    healthcheck:
      test: "mysql -h localhost -u root --password=root -e 'SELECT 1'"
      interval: 5s
      timeout: 5s
      retries: 8
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
